package smart.home.event;

public enum Even_Types {

    SKI, WORKOUT,  CYCLE,  CLEAN, USE_TREADMILL,

    FLOOD,DEVICE_BREAKAGE,DRIVE, HEAT, BABY_SCREAM,
   COOK_IN_MULTICOOKER, LISTEN_TO_MUSIC, PERSON_HUNGRY,  PERSON_THIRSTY, ENTER_ROOM,EXIT_ROOM,

    PLAY,
    ANIMAL_THIRSTY,ANIMAL_HUNGRY
}
