package smart.home.event;

/**
 * Enumeration of event types.
 */
public enum EventTypes {

    SKI, WORKOUT, CYCLE, USE_TREADMILL, CLEAN,

    FLOOD, DEVICE_BREAKAGE, DRIVE, HEAT, BABY_SCREAM,
    COOK_IN_MULTICOOKER, LISTEN_TO_MUSIC, PERSON_HUNGRY, PERSON_THIRSTY, ENTER_ROOM, EXIT_ROOM,

    PLAY,
    ANIMAL_THIRSTY, ANIMAL_HUNGRY
}
